import type {
  BaseGeneratedSchema,
  QueryArgs,
  QueryField,
  QueryParam,
} from '../../client/client.types'

export interface GetQueryParamsOptions {
  /**
   * The name of the field.
   */
  field: QueryField
  /**
   * Arguments passed to the query.
   */
  args?: QueryArgs
  /**
   * The generated schema.
   */
  generatedSchema: BaseGeneratedSchema
}

/**
 * Returns all the query params for a query based on the selected fields.
 *
 * @param options - Options to configure the query params.
 * @returns The query params.
 */
export default function getQueryParams({
  generatedSchema,
  args,
  field,
}: GetQueryParamsOptions): QueryParam[] {
  if (!args) {
    return []
  }

  const currentParams: QueryParam[] = Object.keys(args.variables || {}).map(
    (variable) => ({
      name: variable,
      path: field.name,
      type:
        generatedSchema?.query?.[field.name].__args?.[variable] || field.type,
    }),
  )

  const nestedParams: QueryParam[] = Object.keys(args.select || {})
    .filter((key) => typeof args.select?.[key] !== 'boolean')
    .map((key) =>
      getQueryParams({
        generatedSchema,
        args: args.select?.[key] as QueryArgs,
        field: {
          name: key,
          type: '', // Unknown at this point, will be generated by the recursive call
        },
      }).map((param) => ({
        ...param,
        path: `${field.name}.${param.path}`,
      })),
    )
    .reduce(
      (variables, currentVariables) => [...variables, ...currentVariables],
      [],
    )

  return [...currentParams, ...nestedParams]
}
